name: math
channels:
  - default
dependencies:
  - anaconda::jupyter
  - anaconda::numpy

  - conda-forge::matplotlib
  - conda-forge::pandas
  - conda-forge::pytest
  - conda-forge::scipy
  - conda-forge::scipy
  - conda-forge::sympy
  - conda-forge::watchdog
  - conda-forge::xlsxwriter
