ARG BASE_IMAGE
ARG BASE_TAG

FROM utkusarioglu/${BASE_IMAGE}:${BASE_TAG}

# ARG SCRIPTS_PATH
ARG ENVIRONMENT_NAME 
ARG APT_PACKAGES
ARG APT_PACKAGES_SILENT
ARG PYTHON_VERSION

ARG USERNAME=dev
ARG USER_ID=1000
ARG GROUP=g
ARG GROUP_ID=1000
ARG HOME_ABSPATH=/home/$USERNAME
ARG BOOTSTRAP_ABSPATH=${HOME_ABSPATH}/scripts/bootstrap
ARG VENV_NAME=main
ARG VENV_PATH=${HOME_ABSPATH}/venv/${VENV_NAME}

USER root

WORKDIR ${HOME_ABSPATH}

RUN ls -alR ${HOME_ABSPATH}

COPY home/scripts/ scripts/
COPY ${ENVIRONMENT_NAME}/requirements.txt ${HOME_ABSPATH}/requirements.txt

RUN ls -alR ${HOME_ABSPATH}

RUN ${BOOTSTRAP_ABSPATH}/linux/update-apt.sh

RUN ${BOOTSTRAP_ABSPATH}/python/install-python.sh \
  ${HOME_ABSPATH} \
  ${PYTHON_VERSION} \
  ${VENV_PATH}

RUN ${BOOTSTRAP_ABSPATH}/linux/install-apt.sh --no-check "${APT_PACKAGES_SILENT}"
RUN ${BOOTSTRAP_ABSPATH}/linux/install-apt.sh "${APT_PACKAGES}"

RUN ${BOOTSTRAP_ABSPATH}/linux/clean-apt.sh

# RUN ${BOOTSTRAP_ABSPATH}/python/set-symlinks.sh 

# RUN ${BOOTSTRAP_ABSPATH}/python/set-venv.sh ${HOME_ABSPATH} ${VENV_PATH}


# RUN ${BOOTSTRAP_ABSPATH}/python/install-requirements.sh \
#   ${HOME_ABSPATH} \
#   ${VENV_PATH}

RUN ${BOOTSTRAP_ABSPATH}/linux/set-permissions.sh \
  ${USER_ID} \
  ${GROUP_ID} \
  ${HOME_ABSPATH}

USER ${USER_ID}
# COPY "src/$/requirements.txt" "/requirements.txt"
# RUN source ${VENV_PATH}/bin/activate && \
#   pip install --require-virtualenv -r "/requirements.txt"
