FROM continuumio/miniconda3

ARG ROOT_PASS=
ARG USERNAME=
ARG ENVIRONMENT_NAME= 
ARG ENVIRONMENT_CONFIG=

RUN for arg in ROOT_PASS USERNAME ENVIRONMENT_NAME ENVIRONMENT_CONFIG; \
  do \
  [ ! -z "${arg}" ] || { echo "ARG \"$arg\" needs to be set"; exit 1; } \
  done;

SHELL ["/bin/bash", "-c"]
RUN apt update && apt install \
  vim \
  -y

COPY $ENVIRONMENT_CONFIG /environment.yml
RUN conda env create --file /environment.yml

RUN echo "root:$ROOT_PASS" | chpasswd

RUN useradd -m $USERNAME
USER $USERNAME

# Gists
ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/2d4be44dc7707afccd540ad99ba385e6/raw/3eb6693a91b1aa5b3863d087de1d189b72eeeec8/create-env-example.sh \
  /scripts/create-env-example.sh

ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/3523b00578807d63b05399fe57a4b2a7/raw/7df99dbbeb8ee4d14396be043aef4fbf8fb42ce5/.bashrc \
  /home/$USERNAME/.bashrc

ADD --chown=$USERNAME:$GROUP \
  https://gist.githubusercontent.com/utkusarioglu/d5c216c744460c45bf6260d0de4131b4/raw/d227102e3630a93f8eafcb4d2a5a053d2ae04415/.inputrc \
  /home/$USERNAME/.inputrc
RUN chmod +x \
  /scripts/create-env-example.sh \
  /home/$USERNAME/.bashrc \
  /home/$USERNAME/.inputrc

ENV PATH "/opt/conda/envs/$ENVIRONMENT_NAME/bin:$PATH"
ENV SHELL /bin/bash
# Pushing into `.bashrc` for environment selection
# This line is unique for all containers
RUN source activate $ENVIRONMENT_NAME >> /home/$USERNAME/.bashrc
