name: build-and-push

on:
  workflow_call:
    inputs: 
      image_tag:
        description: Tag of the final docker image
        type: string
        required: true
      base_tag:
        description: Ubuntu base image tag
        type: string
        required: true
    secrets:
      dockerhub_username: 
        required: true
      dockerhub_token: 
        required: true 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
            # Vanilla python
          - dockerfile: src/Dockerfile.python.dev
            container_name: python-devcontainer
            base_image: ubuntu-devcontainer
            image_tag: ${{ inputs.image_tag }}
            base_tag: ${{ inputs.base_tag }}
            python_version: "3.13"
            environment_name: python
            devcontainer_subfolder: python
            dockerhub_readme_path: src/python/DOCKER_README.python.md
            dockerhub_short_description: Devcontainer for python workloads
            apt_packages: ""
            apt_packages_silent: ncurses-bin

          #   # econ
          - dockerfile: src/Dockerfile.conda.dev
            python_version: "3.13"
            container_name: conda-econ-devcontainer
            base_image: ubuntu-devcontainer
            image_tag: ${{ inputs.image_tag }}
            base_tag: ${{ inputs.base_tag }}
            environment_name: econ
            devcontainer_subfolder: econ
            dockerhub_readme_path: src/econ/DOCKER_README.econ.md
            dockerhub_short_description: Devcontainer for economics workloads
            apt_packages: bzip2
            apt_packages_silent: ""

            # music
          - dockerfile: src/Dockerfile.conda.dev
            python_version: "3.13"
            container_name: conda-music-devcontainer
            base_image: ubuntu-devcontainer
            image_tag: ${{ inputs.image_tag }}
            base_tag: ${{ inputs.base_tag }}
            environment_name: music
            devcontainer_subfolder: music
            dockerhub_readme_path: src/music/DOCKER_README.music.md
            dockerhub_short_description: Devcontainer for music workloads
            apt_packages: >-
              pulseaudio 
              lilypond
              bzip2
            apt_packages_silent: >-
              musescore3
              build-essential
              pkg-config
              libjack-dev
              libsdl2-dev
              alsa-utils

          #   # math
          - dockerfile: src/Dockerfile.conda.dev
            python_version: "3.13"
            container_name: conda-math-devcontainer
            base_image: ubuntu-devcontainer
            image_tag: ${{ inputs.image_tag }}
            base_tag: ${{ inputs.base_tag }}
            environment_name: math
            devcontainer_subfolder: math
            dockerhub_readme_path: src/math/DOCKER_README.math.md
            dockerhub_short_description: Devcontainer for mathematics workloads
            apt_packages: >-
              bzip2
            apt_packages_silent: >-
              libsm6 
              libxrender1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build and push ${{ steps.variables.outputs.image_ref }}
        uses: utkusarioglu/devcontainer-build-action@main
        with:
          docker_context: src
          dockerhub_username: ${{ secrets.dockerhub_username }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          image_name: ${{ matrix.images.container_name }}
          image_tag: ${{ matrix.images.image_tag }}
          dockerfile_path: ${{ matrix.images.dockerfile }}
          build_args: |
            BASE_TAG=${{ matrix.images.base_tag }}
            BASE_IMAGE=${{ matrix.images.base_image }}
            ENVIRONMENT_NAME=${{ matrix.images.environment_name }}
            PYTHON_VERSION=${{ matrix.images.python_version }}
            APT_PACKAGES=${{ matrix.images.apt_packages }}
            APT_PACKAGES_SILENT=${{ matrix.images.apt_packages_silent }}
          devcontainer_enabled: "false"
          devcontainer_subfolder: src/${{ matrix.images.devcontainer_subfolder }}
          devcontainer_run_cmd_path: /home/dev/scripts/bootstrap/python/check-devcontainer.sh
          dockerhub_repo_short_description: ${{ matrix.images.dockerhub_short_description }}
          dockerhub_repo_readme_file_path: ${{ matrix.images.dockerhub_readme_path }}
