name: Push

on:
  push

concurrency:
  cancel-in-progress: true
  group: push

jobs:
  push:
    uses: ./.github/workflows/build.wfc.yml
    with:
      image_tag: 3.13-ubuntu-test-30

      # https://hub.docker.com/repository/docker/utkusarioglu/ubuntu-devcontainer/tags
      # base_tag: 2404-test-16
      # base_tag: 2510-test-18
      base_tag: 2404-test-21
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
